---
version: 2.1
jobs:
  first:
    docker:
      - image: archlinux
    steps:
      - checkout
      - run: echo "Hello world"
workflows:
  version: 2.1
  community-gateway:
    jobs:
      - first
