---
- hosts: localhost
  become: true
  gather_facts: false

  vars_files:
  - vars/ansible.json

  tasks:
  - name: Ensure the list of dependencies is fulfilled
    ansible.builtin.pacman:
      name:
        - curl
        - emacs-nox
        - firewalld
        - git
        - go
        - ipset
        - libpam-google-authenticator
        - qrencode
        - tmux
      state: present
  - name: Ensure the TeleIRC repository is cloned
    ansible.builtin.git:
      repo: git://github.com/RITlug/teleirc.git
      dest: /tmp/teleirc
  - name: Ensure the TeleIRC source files are compiled
    ansible.builtin.command: go build cmd/teleirc.go
    args:
      chdir: /tmp/teleirc
  - name: Ensure the TeleIRC binary is in place
    ansible.builtin.copy:
      src: /tmp/teleirc/teleirc
      dest: /usr/local/bin/teleirc
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      mode: "u=rwx,g=rx,o=rx"
      remote_src: true
  - name: Ensure the TeleIRC configuration directory is created
    ansible.builtin.file:
      path: /etc/teleirc
      state: directory
      mode: "u=rw,g=rx,o=rx"
  - name: Ensure the TeleIRC configuration is in place
    ansible.builtin.template:
      src: templates/teleirc-env.j2
      dest: /etc/teleirc/env
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      mode: "u=rw"
      remote_src: true
  - name: Ensure the TeleIRC SystemD service is in place
    ansible.builtin.template:
      src: templates/teleirc.service.j2
      dest: /etc/systemd/system/teleirc.service
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      mode: "u=rw,g=r,o=r"
      remote_src: true
  - name: Ensure the TeleIRC daemon is started and enabled
    ansible.builtin.systemd:
      name: teleirc.service
      state: started
      enabled: true
